#ifndef QFRAMELESSGLOBAL_H
#define QFRAMELESSGLOBAL_H

#include <QtGlobal>

#ifdef SC_FRAMELESS_EXPORTS
#	define SC_FRAMELESS_EXPORT Q_DECL_EXPORT
#else
#	define SC_FRAMELESS_EXPORT Q_DECL_IMPORT
#endif

#endif // QFRAMELESSGLOBAL_H
