include(sdks_common)

if(SC_BUILD_ONLY)
	set(SC_BUILD_ONLY ${SC_BUILD_ONLY})
	set(SC_SDK_BUILD_LIST ${SC_BUILD_ONLY})
	set(SC_SDK_DEPENDENCY_BUILD_LIST "")
	set(SC_TEST_DEPENDENCY_BUILD_LIST "")

	foreach(TARGET IN LISTS SC_BUILD_ONLY)
		message(STATUS "Considering ${TARGET}")
		sc_get_dependencies_for_sdk(${TARGET} DEPENDENCY_LIST)
		if(DEPENDENCY_LIST)
			STRING(REPLACE "," ";" LIST_RESULT ${DEPENDENCY_LIST})
			foreach(DEPENDENCY IN LISTS LIST_RESULT)
                list(APPEND SC_SDK_DEPENDENCY_BUILD_LIST ${DEPENDENCY})
            endforeach()
		endif()
		
		if(SC_ENABLE_TESTING)
			sc_get_dependencies_for_test(${TARGET} DEPENDENCY_LIST)
			if(DEPENDENCY_LIST)
                STRING(REPLACE "," ";" LIST_RESULT ${DEPENDENCY_LIST})
                foreach(DEPENDENCY IN LISTS LIST_RESULT)
                    list(APPEND SC_TEST_DEPENDENCY_BUILD_LIST ${DEPENDENCY})
                endforeach()
            endif()
		endif()
	endforeach()
	
	LIST(REMOVE_DUPLICATES SC_SDK_BUILD_LIST)
    LIST(REMOVE_DUPLICATES SC_SDK_DEPENDENCY_BUILD_LIST)
	LIST(REMOVE_DUPLICATES SC_TEST_DEPENDENCY_BUILD_LIST)
	
	set(SC_TEMP_SDK_DEPENDENCY_BUILD_LIST ${SC_SDK_DEPENDENCY_BUILD_LIST})
	foreach(SDK IN LISTS SC_TEMP_SDK_DEPENDENCY_BUILD_LIST)
		list(FIND SC_SDK_BUILD_LIST ${SDK} DEPENDENCY_INDEX)
		if(DEPENDENCY_INDEX LESS 0)
			set(SDK_DIR "src/${SDK}")
			if (NOT IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${SDK_DIR}")
				message(FATAL_ERROR "${SDK} is required for build, but ${SDK_DIR} directory is missing!")
			endif()
		else()
			list(REMOVE_ITEM SC_SDK_DEPENDENCY_BUILD_LIST ${SDK})
		endif()
	endforeach()
	
	foreach(SDK IN LISTS SC_SDK_DEPENDENCY_BUILD_LIST)
		list(APPEND SC_SDK_BUILD_LIST "${SDK}")
	endforeach()
endif()

function(sc_add_sdk)
	LIST(APPEND EXPORTS "")
	foreach(SDK IN LISTS SC_SDK_BUILD_LIST)
		message(STATUS "Adding ${SDK} to SDK build")
		set(SDK_DIR "src/${SDK}")
		add_subdirectory("${SDK_DIR}")
		LIST(APPEND EXPORTS "${SDK_TARGET}")
		unset(SDK_TARGET)
	endforeach()
	
	if(SC_ENABLE_TESTING)
		foreach(TEST IN LISTS SC_TEST_DEPENDENCY_BUILD_LIST)
			set(TEST_DIR "${CMAKE_SOURCE_DIR}/tests/${TEST}")
			file(GLOB subdirs LIST_DIRECTORIES true "${TEST_DIR}/*")
			foreach(subdir ${subdirs})
				if(EXISTS "${subdir}/CMakeLists.txt")
					add_subdirectory(${subdir})
					get_property(sub_targets DIRECTORY ${subdir} PROPERTY BUILDSYSTEM_TARGETS)
					foreach(target ${sub_targets})
						set_property(TARGET ${target} PROPERTY FOLDER "Tests/${TEST}")
					endforeach()
				endif()
			endforeach()
		endforeach()
	endif()
endfunction()